name: flutter_beacon_example
description: Demonstrates how to use the flutter_beacon plugin.
publish_to: "none"
version: "1.0.0+4"

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_beacon:
    path: ../
  get: ^4.3.6

flutter:
  uses-material-design: true
