name: flutter_beacon
description: Flutter plugin for scanning and transmit as beacon (iBeacon) on Android and iOS.
version: 0.5.1
homepage: https://github.com/alann-maulana/flutter_beacon
publish_to: none

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flu_wake_lock:
    git: https://github.com/sovannDeveloper/wakelock.git
  permission_handler: ^12.0.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterbeacon
        pluginClass: FlutterBeaconPlugin
      ios:
        pluginClass: FlutterBeaconPlugin
